# GENERATE TIME: Sat Jul 16 08:48:17 2022
# CMD:
# C:/Users/ew535/Documents/GitHub/VSR-SIM/basicsr/train.py -opt C:/Users/ew535/Documents/GitHub/VSR-SIM/options/train/VSR-SIM/mixedSet-SIM.yml


# general settings
name: mixedSet_OS-SIM
model_type: SwinIRModel
scale: 1
num_gpu: auto
manual_seed: 1

# dataset and data loader settings
datasets:
  train:
    name: dokumentarer
    type: PairedSIMDataset
    dataroot_gt: E:/datasets/OS-SIM
    dataroot_lq: E:/datasets/OS-SIM
    meta_info_file:
    filename_tmpl: '{}'
    io_backend:
      type: disk

    use_flip: true
    use_rot: true
    gt_size: 512
    patchSize: 128

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: dokumentarer
    type: PairedSIMDataset
    dataroot_gt: E:/datasets/validation
    dataroot_lq: E:/datasets/validation
    gt_size: 512
    patchSize: ~
    io_backend:
      type: disk

# network structures
network_g:
  type: SwinIR_RCAB
  upscale: 1
  in_chans: 3
  img_size: 128
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6]
  embed_dim: 64
  num_heads: [8,8,8,8,8]
  mlp_ratio: 2
  upsampler: ~
  resi_connection: '1conv'
  pixelshuffleFactor: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: 

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    #milestones: [250000, 400000, 450000, 475000]
    #milestones: [10000,25000,40000]
    milestones: [70000,110000,130000]
    gamma: 0.5

  total_iter: 200000 # 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: transformer-sim
    #project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500


